# This workflow will deploy the application to the running environment after a successful merge to main

name: deploy

on:
  workflow_run:
    workflows: [test] # Triggered by the test workflow
    types: [completed] # The test workflow must complete
    branches: [main] # Only when main is updated

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only when test completed successfully
    steps:
      - name: Download latest build
        uses: actions/download-artifact@v3
        with:
          name: chrisbloom7_flaskbb_application_artifact

      - name: Congifure AWS Credentials
        uses: aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Upload application file to AWS
        run: aws s3 cp flaskbb_deploy-${{ github.sha }}.zip s3://flaskbb-corise-chrisbloom7

      - name: Create new application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name your_application_name \
          --source-bundle S3Bucket="flaskbb-corise-chrisbloom7",S3Key="flaskbb_deploy-${{ github.sha }}.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "Application build @ ${{ github.sha }}"

      - name: Deploy application
        run: aws elasticbeanstalk update-environment --environment-name flaskbb-environment --version-label "ver-${{ github.sha }}"
